export const passages = [
  {
    "id": 1,
    "title": "Short Test Passage (Warm-up)",
    "text": "The quick brown fox jumps over the lazy dog. A good typist maintains a steady rhythm and pays close attention to each word. Practice regularly to improve your speed and accuracy."
  },
  {
    "id": 2,
    "title": "Typing Practice Passage 2",
    "text": "Space exploration has entered a thrilling new era, characterized by unprecedented collaboration between government agencies and private companies. Prioritization requires distinguishing between tasks that are urgent and those that yield the highest value over the long term. Effective communication is the cornerstone of any successful organization, encompassing the ability to articulate ideas clearly and listen actively. Space exploration has entered a thrilling new era, characterized by unprecedented collaboration between government agencies and private companies. As we move forward into an era defined by artificial intelligence, it is crucial that we remain mindful of ethical implications. Space exploration has entered a thrilling new era, characterized by unprecedented collaboration between government agencies and private companies. As we move forward into an era defined by artificial intelligence, it is crucial that we remain mindful of ethical implications. However, this rapid progress is not without its challenges, including issues concerning data privacy, cybersecurity, and the digital divide. Time management is an essential skill that enables individuals to maximize productivity and achieve their personal and professional goals. Globalization has reshaped international economies, creating a highly interconnected world through the free flow of goods and services. Public health initiatives recognize the profound impact of nutrition, advocating for a balanced diet rich in essential vitamins. Prioritization requires distinguishing between tasks that are urgent and those that yield the highest value over the long term. Financial literacy empowers individuals to make informed decisions regarding budgeting, saving, investing, and understanding credit systems. Historical preservation connects contemporary society with its cultural heritage, ensuring the stories of previous generations are not lost. In a professional setting, clear communication fosters collaboration, minimizes misunderstandings, and enhances overall team productivity and morale. Prioritization requires distinguishing between tasks that are urgent and those that yield the highest value over the long term. Today, we carry devices in our pockets that are millions of times more powerful than the computers that guided the Apollo missions to the moon. Historical preservation connects contemporary society with its cultural heritage, ensuring the stories of previous generations are not lost. The rapid evolution of technology over the last few decades."
  },
  {
    "id": 3,
    "title": "Typing Practice Passage 3",
    "text": "Financial literacy empowers individuals to make informed decisions regarding budgeting, saving, investing, and understanding credit systems. Effective communication is the cornerstone of any successful organization, encompassing the ability to articulate ideas clearly and listen actively. In the early days of computing, machines were massive, room-sized behemoths that required specialized knowledge just to operate. Historical preservation connects contemporary society with its cultural heritage, ensuring the stories of previous generations are not lost. Prioritization requires distinguishing between tasks that are urgent and those that yield the highest value over the long term. Globalization has reshaped international economies, creating a highly interconnected world through the free flow of goods and services. Globalization has reshaped international economies, creating a highly interconnected world through the free flow of goods and services. Environmental conservation has become a critical issue as the impacts of climate change become increasingly evident worldwide. Furthermore, the advent of the internet has democratized access to information, breaking down barriers that once limited educational and economic opportunities. However, this rapid progress is not without its challenges, including issues concerning data privacy, cybersecurity, and the digital divide. In a professional setting, clear communication fosters collaboration, minimizes misunderstandings, and enhances overall team productivity and morale. In the early days of computing, machines were massive, room-sized behemoths that required specialized knowledge just to operate. Globalization has reshaped international economies, creating a highly interconnected world through the free flow of goods and services. Transitioning to renewable energy sources such as solar and wind power is imperative to reduce our reliance on fossil fuels. Globalization has reshaped international economies, creating a highly interconnected world through the free flow of goods and services. In a professional setting, clear communication fosters collaboration, minimizes misunderstandings, and enhances overall team productivity and morale. Prioritization requires distinguishing between tasks that are urgent and those that yield the highest value over the long term. Prioritization requires distinguishing between tasks that are urgent and those that yield the highest value over the long term. By fostering a culture of responsible innovation, we can ensure that the benefits of technological advancement are shared equitably. Financial literacy."
  },
  {
    "id": 4,
    "title": "Typing Practice Passage 4",
    "text": "Furthermore, the advent of the internet has democratized access to information, breaking down barriers that once limited educational and economic opportunities. Today, we carry devices in our pockets that are millions of times more powerful than the computers that guided the Apollo missions to the moon. Globalization has reshaped international economies, creating a highly interconnected world through the free flow of goods and services. In the early days of computing, machines were massive, room-sized behemoths that required specialized knowledge just to operate. Prioritization requires distinguishing between tasks that are urgent and those that yield the highest value over the long term. Effective communication is the cornerstone of any successful organization, encompassing the ability to articulate ideas clearly and listen actively. Historical preservation connects contemporary society with its cultural heritage, ensuring the stories of previous generations are not lost. The landscape of medical research has undergone a remarkable transformation, driven by a deeper understanding of human biology. The landscape of medical research has undergone a remarkable transformation, driven by a deeper understanding of human biology. The landscape of medical research has undergone a remarkable transformation, driven by a deeper understanding of human biology. Today, we carry devices in our pockets that are millions of times more powerful than the computers that guided the Apollo missions to the moon. Environmental conservation has become a critical issue as the impacts of climate change become increasingly evident worldwide. By fostering a culture of responsible innovation, we can ensure that the benefits of technological advancement are shared equitably. Environmental conservation has become a critical issue as the impacts of climate change become increasingly evident worldwide. As we move forward into an era defined by artificial intelligence, it is crucial that we remain mindful of ethical implications. This digital revolution has brought about unprecedented levels of connectivity, allowing individuals from opposite sides of the globe to interact in real time. Financial literacy empowers individuals to make informed decisions regarding budgeting, saving, investing, and understanding credit systems. Public health initiatives recognize the profound impact of nutrition, advocating for a balanced diet rich in essential vitamins. By fostering."
  },
  {
    "id": 5,
    "title": "Typing Practice Passage 5",
    "text": "This digital revolution has brought about unprecedented levels of connectivity, allowing individuals from opposite sides of the globe to interact in real time. The landscape of medical research has undergone a remarkable transformation, driven by a deeper understanding of human biology. The rapid evolution of technology over the last few decades has fundamentally transformed the way we live, work, and communicate. Financial literacy empowers individuals to make informed decisions regarding budgeting, saving, investing, and understanding credit systems. Transitioning to renewable energy sources such as solar and wind power is imperative to reduce our reliance on fossil fuels. Historical preservation connects contemporary society with its cultural heritage, ensuring the stories of previous generations are not lost. By fostering a culture of responsible innovation, we can ensure that the benefits of technological advancement are shared equitably. Prioritization requires distinguishing between tasks that are urgent and those that yield the highest value over the long term. This digital revolution has brought about unprecedented levels of connectivity, allowing individuals from opposite sides of the globe to interact in real time. Effective communication is the cornerstone of any successful organization, encompassing the ability to articulate ideas clearly and listen actively. The delicate balance of our ecosystems is threatened by deforestation, pollution, and the over-extraction of natural resources. Space exploration has entered a thrilling new era, characterized by unprecedented collaboration between government agencies and private companies. Furthermore, the advent of the internet has democratized access to information, breaking down barriers that once limited educational and economic opportunities. This digital revolution has brought about unprecedented levels of connectivity, allowing individuals from opposite sides of the globe to interact in real time. Public health initiatives recognize the profound impact of nutrition, advocating for a balanced diet rich in essential vitamins. Historical preservation connects contemporary society with its cultural heritage, ensuring the stories of previous generations are not lost. Environmental conservation has become a critical issue as the impacts of climate change become increasingly evident worldwide. This digital revolution has brought about unprecedented levels of connectivity, allowing individuals from opposite sides of the globe to interact in real time."
  },
  {
    "id": 6,
    "title": "Typing Practice Passage 6",
    "text": "By fostering a culture of responsible innovation, we can ensure that the benefits of technological advancement are shared equitably. In a professional setting, clear communication fosters collaboration, minimizes misunderstandings, and enhances overall team productivity and morale. As we move forward into an era defined by artificial intelligence, it is crucial that we remain mindful of ethical implications. Effective communication is the cornerstone of any successful organization, encompassing the ability to articulate ideas clearly and listen actively. The delicate balance of our ecosystems is threatened by deforestation, pollution, and the over-extraction of natural resources. Globalization has reshaped international economies, creating a highly interconnected world through the free flow of goods and services. Space exploration has entered a thrilling new era, characterized by unprecedented collaboration between government agencies and private companies. However, this rapid progress is not without its challenges, including issues concerning data privacy, cybersecurity, and the digital divide. Public health initiatives recognize the profound impact of nutrition, advocating for a balanced diet rich in essential vitamins. Prioritization requires distinguishing between tasks that are urgent and those that yield the highest value over the long term. In the early days of computing, machines were massive, room-sized behemoths that required specialized knowledge just to operate. Today, we carry devices in our pockets that are millions of times more powerful than the computers that guided the Apollo missions to the moon. Globalization has reshaped international economies, creating a highly interconnected world through the free flow of goods and services. Furthermore, the advent of the internet has democratized access to information, breaking down barriers that once limited educational and economic opportunities. Prioritization requires distinguishing between tasks that are urgent and those that yield the highest value over the long term. Furthermore, the advent of the internet has democratized access to information, breaking down barriers that once limited educational and economic opportunities. Financial literacy empowers individuals to make informed decisions regarding budgeting, saving, investing, and understanding credit systems. In the early days of computing, machines were massive, room-sized behemoths that required specialized knowledge just to operate. Financial literacy empowers individuals to make informed decisions regarding."
  },
  {
    "id": 7,
    "title": "Typing Practice Passage 7",
    "text": "Historical preservation connects contemporary society with its cultural heritage, ensuring the stories of previous generations are not lost. This digital revolution has brought about unprecedented levels of connectivity, allowing individuals from opposite sides of the globe to interact in real time. Public health initiatives recognize the profound impact of nutrition, advocating for a balanced diet rich in essential vitamins. Environmental conservation has become a critical issue as the impacts of climate change become increasingly evident worldwide. Environmental conservation has become a critical issue as the impacts of climate change become increasingly evident worldwide. Today, we carry devices in our pockets that are millions of times more powerful than the computers that guided the Apollo missions to the moon. Public health initiatives recognize the profound impact of nutrition, advocating for a balanced diet rich in essential vitamins. The delicate balance of our ecosystems is threatened by deforestation, pollution, and the over-extraction of natural resources. Historical preservation connects contemporary society with its cultural heritage, ensuring the stories of previous generations are not lost. In a professional setting, clear communication fosters collaboration, minimizes misunderstandings, and enhances overall team productivity and morale. Financial literacy empowers individuals to make informed decisions regarding budgeting, saving, investing, and understanding credit systems. In a professional setting, clear communication fosters collaboration, minimizes misunderstandings, and enhances overall team productivity and morale. Globalization has reshaped international economies, creating a highly interconnected world through the free flow of goods and services. The landscape of medical research has undergone a remarkable transformation, driven by a deeper understanding of human biology. Public health initiatives recognize the profound impact of nutrition, advocating for a balanced diet rich in essential vitamins. Environmental conservation has become a critical issue as the impacts of climate change become increasingly evident worldwide. Prioritization requires distinguishing between tasks that are urgent and those that yield the highest value over the long term. The delicate balance of our ecosystems is threatened by deforestation, pollution, and the over-extraction of natural resources. By fostering a culture of responsible innovation, we can ensure that the benefits of technological advancement are shared equitably. However, this rapid."
  },
  {
    "id": 8,
    "title": "Typing Practice Passage 8",
    "text": "Today, we carry devices in our pockets that are millions of times more powerful than the computers that guided the Apollo missions to the moon. Globalization has reshaped international economies, creating a highly interconnected world through the free flow of goods and services. Transitioning to renewable energy sources such as solar and wind power is imperative to reduce our reliance on fossil fuels. Financial literacy empowers individuals to make informed decisions regarding budgeting, saving, investing, and understanding credit systems. Historical preservation connects contemporary society with its cultural heritage, ensuring the stories of previous generations are not lost. Transitioning to renewable energy sources such as solar and wind power is imperative to reduce our reliance on fossil fuels. Globalization has reshaped international economies, creating a highly interconnected world through the free flow of goods and services. Public health initiatives recognize the profound impact of nutrition, advocating for a balanced diet rich in essential vitamins. The delicate balance of our ecosystems is threatened by deforestation, pollution, and the over-extraction of natural resources. This digital revolution has brought about unprecedented levels of connectivity, allowing individuals from opposite sides of the globe to interact in real time. In a professional setting, clear communication fosters collaboration, minimizes misunderstandings, and enhances overall team productivity and morale. The rapid evolution of technology over the last few decades has fundamentally transformed the way we live, work, and communicate. Globalization has reshaped international economies, creating a highly interconnected world through the free flow of goods and services. Furthermore, the advent of the internet has democratized access to information, breaking down barriers that once limited educational and economic opportunities. Historical preservation connects contemporary society with its cultural heritage, ensuring the stories of previous generations are not lost. Effective communication is the cornerstone of any successful organization, encompassing the ability to articulate ideas clearly and listen actively. The delicate balance of our ecosystems is threatened by deforestation, pollution, and the over-extraction of natural resources. The rapid evolution of technology over the last few decades has fundamentally transformed the way we live, work, and communicate. Historical preservation connects contemporary society with its."
  },
  {
    "id": 9,
    "title": "Typing Practice Passage 9",
    "text": "By fostering a culture of responsible innovation, we can ensure that the benefits of technological advancement are shared equitably. Globalization has reshaped international economies, creating a highly interconnected world through the free flow of goods and services. Today, we carry devices in our pockets that are millions of times more powerful than the computers that guided the Apollo missions to the moon. Prioritization requires distinguishing between tasks that are urgent and those that yield the highest value over the long term. Today, we carry devices in our pockets that are millions of times more powerful than the computers that guided the Apollo missions to the moon. Public health initiatives recognize the profound impact of nutrition, advocating for a balanced diet rich in essential vitamins. Effective communication is the cornerstone of any successful organization, encompassing the ability to articulate ideas clearly and listen actively. Historical preservation connects contemporary society with its cultural heritage, ensuring the stories of previous generations are not lost. However, this rapid progress is not without its challenges, including issues concerning data privacy, cybersecurity, and the digital divide. Prioritization requires distinguishing between tasks that are urgent and those that yield the highest value over the long term. The landscape of medical research has undergone a remarkable transformation, driven by a deeper understanding of human biology. Transitioning to renewable energy sources such as solar and wind power is imperative to reduce our reliance on fossil fuels. Time management is an essential skill that enables individuals to maximize productivity and achieve their personal and professional goals. Globalization has reshaped international economies, creating a highly interconnected world through the free flow of goods and services. Effective communication is the cornerstone of any successful organization, encompassing the ability to articulate ideas clearly and listen actively. The landscape of medical research has undergone a remarkable transformation, driven by a deeper understanding of human biology. Furthermore, the advent of the internet has democratized access to information, breaking down barriers that once limited educational and economic opportunities. Public health initiatives recognize the profound impact of nutrition, advocating for a balanced diet rich in essential vitamins."
  },
  {
    "id": 10,
    "title": "Typing Practice Passage 10",
    "text": "As we move forward into an era defined by artificial intelligence, it is crucial that we remain mindful of ethical implications. Public health initiatives recognize the profound impact of nutrition, advocating for a balanced diet rich in essential vitamins. The delicate balance of our ecosystems is threatened by deforestation, pollution, and the over-extraction of natural resources. However, this rapid progress is not without its challenges, including issues concerning data privacy, cybersecurity, and the digital divide. The delicate balance of our ecosystems is threatened by deforestation, pollution, and the over-extraction of natural resources. Globalization has reshaped international economies, creating a highly interconnected world through the free flow of goods and services. Public health initiatives recognize the profound impact of nutrition, advocating for a balanced diet rich in essential vitamins. This digital revolution has brought about unprecedented levels of connectivity, allowing individuals from opposite sides of the globe to interact in real time. Time management is an essential skill that enables individuals to maximize productivity and achieve their personal and professional goals. Transitioning to renewable energy sources such as solar and wind power is imperative to reduce our reliance on fossil fuels. Effective communication is the cornerstone of any successful organization, encompassing the ability to articulate ideas clearly and listen actively. Environmental conservation has become a critical issue as the impacts of climate change become increasingly evident worldwide. Globalization has reshaped international economies, creating a highly interconnected world through the free flow of goods and services. Today, we carry devices in our pockets that are millions of times more powerful than the computers that guided the Apollo missions to the moon. Public health initiatives recognize the profound impact of nutrition, advocating for a balanced diet rich in essential vitamins. Space exploration has entered a thrilling new era, characterized by unprecedented collaboration between government agencies and private companies. Space exploration has entered a thrilling new era, characterized by unprecedented collaboration between government agencies and private companies. Public health initiatives recognize the profound impact of nutrition, advocating for a balanced diet rich in essential vitamins. The delicate balance of our ecosystems is threatened by."
  },
  {
    "id": 11,
    "title": "Typing Practice Passage 11",
    "text": "This digital revolution has brought about unprecedented levels of connectivity, allowing individuals from opposite sides of the globe to interact in real time. Historical preservation connects contemporary society with its cultural heritage, ensuring the stories of previous generations are not lost. Today, we carry devices in our pockets that are millions of times more powerful than the computers that guided the Apollo missions to the moon. By fostering a culture of responsible innovation, we can ensure that the benefits of technological advancement are shared equitably. Environmental conservation has become a critical issue as the impacts of climate change become increasingly evident worldwide. Transitioning to renewable energy sources such as solar and wind power is imperative to reduce our reliance on fossil fuels. However, this rapid progress is not without its challenges, including issues concerning data privacy, cybersecurity, and the digital divide. Time management is an essential skill that enables individuals to maximize productivity and achieve their personal and professional goals. Today, we carry devices in our pockets that are millions of times more powerful than the computers that guided the Apollo missions to the moon. Financial literacy empowers individuals to make informed decisions regarding budgeting, saving, investing, and understanding credit systems. In a professional setting, clear communication fosters collaboration, minimizes misunderstandings, and enhances overall team productivity and morale. By fostering a culture of responsible innovation, we can ensure that the benefits of technological advancement are shared equitably. Space exploration has entered a thrilling new era, characterized by unprecedented collaboration between government agencies and private companies. The delicate balance of our ecosystems is threatened by deforestation, pollution, and the over-extraction of natural resources. Globalization has reshaped international economies, creating a highly interconnected world through the free flow of goods and services. This digital revolution has brought about unprecedented levels of connectivity, allowing individuals from opposite sides of the globe to interact in real time. The delicate balance of our ecosystems is threatened by deforestation, pollution, and the over-extraction of natural resources. This digital revolution has brought about unprecedented levels of connectivity, allowing individuals from opposite sides of the globe to interact."
  }
];
